language: android
jdk: oraclejdk8

env:
    global:
        - ANDROID_TARGET=android-27
        - ANDROID_ABI=x86 # x86 might run on Travis if hardware accelartion is disabled 

# Install SDK tools
before_install:
    - source ./install-sdk-tools.sh # Run script and collect environment variables

# Install NDK, System Images, and other components
install:
    - echo y | sdkmanager "ndk-bundle" > /dev/null
    - echo y | sdkmanager "platform-tools"  > /dev/null
    - echo y | sdkmanager "build-tools;27.0.3" > /dev/null
    - echo y | sdkmanager "platforms;${ANDROID_TARGET}" > /dev/null
    - echo y | sdkmanager "extras;android;m2repository" > /dev/null
    - echo y | sdkmanager "system-images;${ANDROID_TARGET};google_apis;${ANDROID_ABI}" > /dev/null
    - echo y | sdkmanager "cmake;3.6.4111459" > /dev/null

before_script:
    - echo no | avdmanager create avd --force --name test --package "system-images;${ANDROID_TARGET};google_apis;${ANDROID_ABI}" --abi ${ANDROID_ABI} --device pixel

# Run test suite
script:
    - chmod +x *.sh
    - ./test.sh

# Cache
before_cache:
    - rm -r $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

# Build succeeded
after_success:
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports" # Collect coverage data
    - curl https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh > send.sh && chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL # Webhook to Discord

# Build failed
after_failure:
    - curl https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh > send.sh && chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL # Webhook to Discord
