language: android
jdk: oraclejdk7

before_cache:
    - rm -r $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
env:
    global:
        - ANDROID_TARGET=android-26
        - ANDROID_ABI=armeabi-v7a
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-26.0.2
        - android-26
        - extra-android-m2repository
        - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
    - ./gradlew build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
